version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./app:/app"
      - "/material:/app/material"
      - "/material:/app/material.frontend"

    ports:
      - "8000:8000"
